import pyautogui

pyautogui.PAUSE = 3
pyautogui.click(pyautogui.locateCenterOnScreen('Search.png'))
#pyautogui.click(10, 55)
pyautogui.typewrite('Firefox') 
pyautogui.doubleClick(135,135)
#pyautogui.click(135,135)
pyautogui.click(285,75)
#pyautogui.typewrite(['h','t','t','p','s',':','/','/','a','c','c','o','u','n','t','s','.','g','o','o','g','l','e'])
#pyautogui.typewrite(['.','c','o','m','/','s','i','g','n','u','p','/','v','2','/','w','e','b','c','r','e','a','t','e'])
#pyautogui.typewrite(['a','c','c','o','u','n','t','?','h','l','=','e','n','&','f','l','o','w','N','a','m','e','=','G','l','i','f','W','e','b','S','i','g','n','I','n','&','f','l','o','w','E','n','t','r','y','=','S','i','g','n','U','p'])
link='https://accounts.google.com/signup/v2/webcreateaccount?hl=en&flowName=GlifWebSignIn&flowEntry=SignUp'
for i in link:
    pyautogui.typewrite(i)
pyautogui.typewrite('\n')
pyautogui.click(400,100)
pyautogui.typewrite('\t')
pyautogui.typewrite('Arvind')
pyautogui.typewrite('\t')
pyautogui.typewrite('Kumar')
pyautogui.typewrite('\t')
pyautogui.typewrite('ArvindKumartest12')
pyautogui.typewrite('\t')
pyautogui.typewrite('\t')
pyautogui.typewrite('')
pyautogui.typewrite('\t')   
pyautogui.typewrite('')
pyautogui.typewrite('\t')   
pyautogui.typewrite('\t')
pyautogui.typewrite('\n')
pyautogui.click(600,300)
pyautogui.press('\t')
pyautogui.press('\t')
pyautogui.press('\t')
pyautogui.press('\t')
pyautogui.typewrite('down')
pyautogui.press('\t')
pyautogui.typewrite('23')
pyautogui.press('\t')
pyautogui.typewrite('1990')
pyautogui.press('\t')
pyautogui.typewrite('down')
pyautogui.press('\t')
pyautogui.press('\t')
pyautogui.typewrite('\n')
pyautogui.click(400,400)
for i in range(10):
    pyautogui.scroll(-50)
pyautogui.doubleClick(pyautogui.locateCenterOnScreen('agree.png'))
